name: GitHub Actions
on: [push]
jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kube_project:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kube_project:latest 

  azure-deployment:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
    - name: Install kubectl
      run: sudo apt-get update && sudo snap install kubectl --classic

    - name: Install Azure CLI
      run: sudo apt-get -y update && sudo apt-get -y install azure-cli && az
    
    - name: Connect Azure Cloud
      run: az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.AZ_SECRET }} --tenant ${{ secrets.TENANT_ID }}

    - name: Get Azure kubernetes cluster informations
      run: az aks get-credentials --resource-group hitema_kube --name hitema

    - name: actual directory
      run: pwd 

    - name: List files at project root
      run: ls -la

    - name: Update Kubernetes cluster
      run: kubectl apply -f caps_pod.yaml