name: GitHub Actions
on: [push]
jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kube_project:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kube_project:latest 

  azure-deployment:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install kubectl
      run: sudo apt-get update && sudo snap install kubectl --classic

    - name: Install Azure CLI
      run: sudo apt-get -y update && sudo apt-get -y install azure-cli && az
    
    - name: Connect Azure Cloud
      run: az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.AZ_SECRET }} --tenant ${{ secrets.TENANT_ID }}

    - name: Get Azure kubernetes cluster informations
      run: az aks get-credentials --resource-group hitema_kube --name hitema

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f caps_deployment.yml
        kubectl apply -f caps_service.yml

    - name: Get external IP address
      run: |
        EXTERNAL_IP=$(kubectl get svc caps-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "External IP address: $EXTERNAL_IP"

  terraform-deployment:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve



    